export const SET_MODE = "SET_MODE";
export const SET_NAME = "SET_NAME";
export const SET_PERSON_INVOLVED = "SET_PERSON_INVOLVED";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_INCIDENT_TYPE = "SET_INCIDENT_TYPE";
